<?php

class Stats {
	const NAME = 'name';
	const RACE = 'race';
	const CLASS_NAME = 'class';
	const HP_BASE = 'hp_base';
	const HP_TEMP = 'hp_temp';
	const HP_TOTAL = 'hp_total';	
	const HP_MAX = 'hp_max';
	const AC_BASE = 'ac_base';
	const AC_TEMP = 'ac_temp';
	const AC_TOTAL = 'ac_total';
	const AC_BONUS_ITEMS = 'ac_bonus_items';
	const AC_BONUS_EFFECTS = 'ac_bonus_effects';
	const STR_BASE = 'str_base';
	const STR_TEMP = 'str_temp';
	const STR_TOTAL = 'str_total';
	const STR_BONUS_ITEMS = 'str_bonus_items';
	const STR_BONUS_EFFECTS = 'str_bonus_effects';
	const DEX_BASE = 'dex_base';
	const DEX_TEMP = 'dex_temp';
	const DEX_TOTAL = 'dex_total';
	const DEX_BONUS_ITEMS = 'dex_bonus_items';
	const DEX_BONUS_EFFECTS = 'dex_bonus_effects';
	const INT_BASE = 'int_base';
	const INT_TEMP = 'int_temp';
	const INT_TOTAL = 'int_total';
	const INT_BONUS_ITEMS = 'int_bonus_items';
	const INT_BONUS_EFFECTS = 'int_bonus_effects';
	const EQUIPPED = 'equipped';
	const EQUIPPED_MELEE = 'equipped_melee';
	const EQUIPPED_RANGED = 'equipped_ranged';
	const EQUIPPED_ARMOR = 'equipped_armor';
	const BACKPACK = 'backpack';
	const BACKPACK_MELEE = 'backpack_melee';
	const BACKPACK_RANGED = 'backpack_ranged';
	const BACKPACK_ARMOR = 'backpack_armor';
	const BACKPACK_ARROWS = 'backpack_arrows';
	const POTION_BAG = 'potion_bag';
	const POTION_HEAL = 'potion_heal';
	const POTION_ATK = 'potion_atk';
	const POTION_DEF = 'potion_def';
	const POTION_INT = 'potion_int';
	const POTION_DEX = 'potion_dex';
	const CLASS_DESCRIPTION = 'class_description';
	public $name;
	public $race;
	public $class;
	public $hp_base;
	public $hp_temp;
	public $hp_total;
	public $hp_max;
	public $ac_base;
	public $ac_temp;
	public $ac_total;
	public $ac_bonus_items;
	public $ac_bonus_effects;
	public $str_base;
	public $str_temp;
	public $str_total;
	public $str_bonus_items;
	public $str_bonus_effects;
	public $dex_base;
	public $dex_temp;
	public $dex_total;
	public $dex_bonus_items;
	public $dex_bonus_effects;
	public $int_base;
	public $int_temp;
	public $int_total;
	public $int_bonus_items;
	public $int_bonus_effects;
	public $equipped;
	public $backpack;
	public $potion_bag;
	public $class_description;
}
